### ISSUE TITLE
TODO: Reventh Sharma

### ISSUE THREAD

**Issue by Reventh-Sharma** [Reventh-Sharma/DSC-250-LMTutor#2]
- [x] Python code to run LMTutor backend on server
- [x] Given Question and Document number, recall metric for extracting relevant document
- [x] Add other slides of Prof. Zhiting in database
- [x] Metric suggestion: Increase the number of unrelated documents and see how the relevance metrics are performing
